In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [21]:
df= pd.read_csv("homeprices.csv")

In [22]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [23]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [24]:
median=df["bedrooms"].median()

In [25]:
def sai(df,variable,median): #impute nan(dataset,feature name,mean or median or mode)
    df[variable+'_median']=df[variable].fillna(median) #fillna is used to fill the values 

impute_nan(df,bedrooms,median)

In [26]:
sai(df,"bedrooms",median)

In [27]:
df.head()

area  bedrooms  age   price  bedrooms_median
0  2600       3.0   20  550000              3.0
1  3000       4.0   15  565000              4.0
2  3200       NaN   18  610000              4.0
3  3600       3.0   30  595000              3.0
4  4000       5.0    8  760000              5.0

In [28]:
df=df.drop("bedrooms",axis=1)

In [29]:
df

area  age   price  bedrooms_median
0  2600   20  550000              3.0
1  3000   15  565000              4.0
2  3200   18  610000              4.0
3  3600   30  595000              3.0
4  4000    8  760000              5.0
5  4100    8  810000              6.0

In [33]:
X=df.drop("price",axis=1)
y=df["price"]

In [34]:
X

area  age  bedrooms_median
0  2600   20              3.0
1  3000   15              4.0
2  3200   18              4.0
3  3600   30              3.0
4  4000    8              5.0
5  4100    8              6.0

In [35]:
y

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [37]:
X_test

area  age  bedrooms_median
5  4100    8              6.0
2  3200   18              4.0

In [38]:
y_test

5    810000
2    610000
Name: price, dtype: int64

In [39]:
X_train

area  age  bedrooms_median
1  3000   15              4.0
3  3600   30              3.0
0  2600   20              3.0
4  4000    8              5.0

In [40]:
from sklearn.linear_model import LinearRegression

In [43]:
sai=LinearRegression()

In [44]:
model=sai.fit(X_train,y_train)

In [45]:
sai.coef_

array([    236.25,  -19125.  , -175125.  ])

In [46]:
sai.intercept_

843625.0000000003

In [32]:
y_predict=model.predict(X_test)

In [33]:
y_predict

array([608500., 554875.])

In [34]:
y_pre=model.predict([[4100,8,6]])

In [35]:
y_pre

array([608500.])

In [47]:
model.predict([[4500,8,10]])

array([2500.])

In [48]:
model.score(X_train,y_train)

1.0

In [78]:
df= pd.read_csv("homeprices.csv")

In [79]:
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [82]:
df_bedrooms=df["bedrooms"].median()

In [83]:
df["bedrooms"]=df["bedrooms"].fillna(df_bedrooms)

In [84]:
df["bedrooms"]

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [85]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000